# Generated by Django 3.1.5 on 2021-01-24 18:01

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.CharField(blank=True, choices=[('led', 'LED TV'), ('lcd', 'LCD TV'), ('plasma', 'PLASMA TV')], max_length=200, null=True)),
                ('brand', models.CharField(blank=True, choices=[('Akai', 'Akai'), ('Aiwa', 'Aiwa'), ('BPL', 'BPL'), ('Daewoo', 'Daewoo'), ('Haier', 'Haier'), ('Hyundai', 'Hyundai'), ('Hitachi', 'Hitachi'), ('Koryo', 'Koryo'), ('LG', 'LG'), ('Lyod', 'Lyod'), ('Mitsubishi', 'Mitsubishi'), ('Onida', 'Onida'), ('Philips', 'Philips'), ('Panasonic', 'Panasonic'), ('Pioneer', 'Pioneer'), ('Sanyo', 'Sanyo'), ('Sharp', 'Sharp'), ('Samsung', 'Samsung'), ('Sansui', 'Sansui'), ('Toshiba', 'Toshiba'), ('Thomson', 'Thomson'), ('Texla', 'Texla'), ('Videocon', 'Videocon'), ('IMPORTED Product', 'IMPORTED Product'), ('Other COMPANY/BRAND', 'Other COMPANY/BRAND')], max_length=200, null=True)),
                ('service', models.CharField(blank=True, choices=[('Repairing', 'Repairing'), ('Installation', 'Installation')], max_length=200, null=True)),
                ('message', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Enquiry',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('topic', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_topic', models.CharField(blank=True, max_length=50, null=True)),
                ('discription', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Slider',
            },
        ),
    ]
