# Generated by Django 3.1.5 on 2021-02-01 13:38

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20210124_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('discription', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('discription2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Why Choose Us',
            },
        ),
    ]
