# Generated by Django 3.1.5 on 2021-02-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_whyus'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='address',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
